spring:
  application:
    name: api
  config:
    import: file:infrastructure/src/main/resources/application.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${api.base-url}/api/${api.version}/auth/google/callback
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

api:
  version: v1
  base-url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION} # 3600000 1시간 (밀리초 단위)
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION} # 86400000 1일 (밀리초 단위)